http:
  port: "8081"

rabbitmq:
  host: "localhost"
  port: "5672"
  virtualHost: "dev"
  username: "guest"
  password: "guest"
  empexchange: "employee-exchange"
  empqueue: "employee-queue"
  empretryqueue: "employee-retry-queue"
  emperrorqueue: "employee-error-queue"
  empdelayqueue: "employee-delay-queue"



retry:
  threshold: "3"
  ttl: "5"
